[project]
name = "bot09"
version = "0.1.0"
description = "bot09"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" }
]
plugins = ["nonebot_plugin_reboot", "nonebot_plugin_apscheduler", "nonebot_plugin_htmlrender"]
plugin_dirs = ["bot09/plugins"]
builtin_plugins = ["echo"]
